services:
        web:
                image: pyre 
                build: .
                ports:
                        - "8505:8505"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
